### ISSUE TITLE
DHT Sensor gives wrong data

### ISSUE THREAD

**Issue by grigoryshatalin** [grigoryshatalin/AkvelonInternshipMicroController#2]

**Comment by SanderGi** [comment]
Can you add some screenshots/example data that you believe is wrong? The outputs I get seem accurate

**Comment by SanderGi** [comment]
If something is wrong, the library has instructions for calibration that we can go through (we should probably do this anyway). It is expected that every device is slightly different within the manufacturer's tolerances

**Comment by grigoryshatalin** [comment]
Deprecated code
